name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input for the workflow'
        required: false
        default: 'default value'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Foo
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: "ndla-h5p-caretaker"
          SVN_DIR: "svn_checkout"  # Directory to check out the SVN repo
        run: |
          echo "Using SVN_USERNAME: $SVN_USERNAME"
          echo "Using SVN_PASSWORD: $SVN_PASSWORD"
          echo "Using SLUG: $SLUG"

          # Check out the SVN repository
          svn co --depth=empty "https://plugins.svn.wordpress.org/${SLUG}" "$SVN_DIR"
          svn up --set-depth=infinity "$SVN_DIR/trunk"
          svn up --set-depth=infinity "$SVN_DIR/tags"

          # Remove the file ndla-h5p-caretaker.zip from trunk
          if [ -f "$SVN_DIR/trunk/ndla-h5p-caretaker.zip" ]; then
            echo "Removing ndla-h5p-caretaker.zip from trunk"
            svn delete "$SVN_DIR/trunk/ndla-h5p-caretaker.zip"
          else
            echo "File ndla-h5p-caretaker.zip not found in trunk"
          fi

          # Commit the changes to the SVN repository
          svn commit -m "Removed ndla-h5p-caretaker.zip from trunk" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" "$SVN_DIR/trunk/ndla-h5p-caretaker.zip"
